In [1]:
import numpy as np

In [2]:
x=np.zeros((3,4))

In [3]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x=np.ones((2,3,4) , dtype='int16')

In [5]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
x=np.linspace(0,2,9)

In [7]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
x=np.full((2,2),7)

In [9]:
x

array([[7, 7],
       [7, 7]])

In [10]:
x=np.eye(2,2)

In [11]:
x

array([[1., 0.],
       [0., 1.]])

In [12]:
x=np.random.random((2,2))